import { ShieldCheck, Shield, Info, CheckCircle2 } from 'lucide-react'
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Separator } from '@/components/ui/separator'

const CATEGORY_INFO = {
  c2pa: { name: 'C2PA Manifest', description: 'Content credentials and provenance data', variant: 'destructive' },
  exif: { name: 'EXIF Data', description: 'Camera settings, location, and timestamps', variant: 'secondary' },
  xmp: { name: 'XMP Tags', description: 'Software-specific metadata and keywords', variant: 'secondary' },
  other: { name: 'Other Metadata', description: 'ICC profiles and other chunks', variant: 'outline' },
}

function formatSize(bytes) {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

export function MetadataDiff({ metadata, originalSize, strippedSize }) {

  const hasMetadata = metadata && metadata.length > 0
  const sizeReduction = originalSize && strippedSize ? originalSize - strippedSize : 0

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-sm font-medium">
          {hasMetadata ? (
            <Shield className="size-4 text-destructive" />
          ) : (
            <ShieldCheck className="size-4" />
          )}
          {hasMetadata ? `Metadata found — ${metadata.length} items stripped` : 'No metadata found'}
        </CardTitle>
      </CardHeader>
      <CardContent className="flex flex-col gap-4">
        {hasMetadata ? (
          <>
            <div className="flex flex-col gap-3">
              {Object.entries(
                metadata.reduce((acc, m) => {
                  const cat = m.category || 'other'
                  if (!acc[cat]) acc[cat] = []
                  acc[cat].push(m)
                  return acc
                }, {}),
              ).map(([category, items]) => {
                const info = CATEGORY_INFO[category] || CATEGORY_INFO.other
                return (
                  <div
                    key={category}
                    className="flex items-start justify-between rounded-lg bg-muted/30 p-3"
                  >
                    <div>
                      <p className="text-sm font-medium">{info.name}</p>
                      <p className="text-xs text-muted-foreground">{info.description}</p>
                      {items
                        .filter((m) => m.value)
                        .map((m, i) => (
                          <p key={i} className="text-xs text-muted-foreground mt-1">
                            {m.type}: {m.value}
                          </p>
                        ))}
                    </div>
                    <div className="flex items-center gap-2">
                      <Badge variant={info.variant}>
                        {items.length} found
                      </Badge>
                      <Badge variant="outline" className="text-destructive border-destructive/30 bg-destructive/5">
                        Removed
                      </Badge>
                    </div>
                  </div>
                )
              })}
              {sizeReduction > 0 && (
                <>
                  <Separator />
                  <div className="flex items-center gap-2 text-sm">
                    <CheckCircle2 className="size-4 text-chart-2" />
                    <span>
                      Size reduced from {formatSize(originalSize)} to{' '}
                      {formatSize(strippedSize)} (
                      {((sizeReduction / originalSize) * 100).toFixed(1)}% smaller)
                    </span>
                  </div>
                </>
              )}
            </div>
          </>
        ) : (
          <div className="flex items-start gap-3">
            <Info className="size-5 mt-0.5 shrink-0 text-muted-foreground" />
            <p className="text-sm text-muted-foreground">
              No EXIF, XMP, or C2PA metadata was detected in this image.
            </p>
          </div>
        )}

        <div className="flex items-start gap-3 rounded-lg bg-primary/5 p-4 border border-primary/10">
          <Info className="size-5 mt-0.5 shrink-0 text-primary/70" />
          <p className="text-xs leading-relaxed text-primary/80">
            The cleaned version is generated by extracting raw pixel data and re-encoding it
            via Canvas API. This process naturally discards all non-pixel data chunks,
            ensuring 100% metadata removal.
          </p>
        </div>
      </CardContent>
    </Card>
  )
}
